### ISSUE TITLE
`pathSubstitutions` seems doesn't work.

### ISSUE THREAD

**Issue by Abbyyan** [WebFreak001/code-debug#246]
I'm using the `code-debug` extension to debug C++ with ssh and it works well. But now i'm confused about the `pathSubstitutions` configuration. In my situation, the executable saved the location of the original source code `/path-to-source/srcA`, which right now is populated by a different version with the same file names. And i moved the original source code to a new  path `/path-to-source/origin/srcB` . I want to point GDB to the new path `/path-to-source/origin/srcB`, so i add `pathSubstitutions` on my `launch.json` as follows.
```shell
      "type": "gdb",
      "request": "attach",
      "name": "Test",
      "executable": "bin-out/mmo2osample",
     ...
      "pathSubstitutions": {
          "/path-to-source/srcA": "/path-to-source/origin/srcB"
      }
```
But it seems doesn't work. According to  https://github.com/WebFreak001/code-debug/blob/4254bb15a616e99ba1a8e68aefa4d3babe0bb7b6/src/gdb.ts#L189,  the `pathSubstitutions` add a `substitute-path` arg while running the gdb.  How should I use this parameter, or whether this parameter can achieve my desired goal please? Hope for your help. Thanks a lot.

**Comment by GitMensch** [comment]
The definition looks fine for me, but I'm not sure that [`substitute-path`](https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html#set-substitute_002dpath) is applied by GDB in your case - which is "I do have the files in A but different ones".
I suggest you try what happens if you rename /path-to-source/srcA".
... and in any case: those are **path** substitutions, not **file-name** ones.

**Comment by GitMensch** [comment]
.. possibly close this one?

**Comment by Abbyyan** [comment]
> .. possibly close this one?

Got it. Thanks a lot.
