### ISSUE TITLE
debugging x64 assembly

### ISSUE THREAD

**Issue by Epikest** [WebFreak001/code-debug#275]
how do i use this extension to debug x64 assembly on windows?

**Comment by GitMensch** [comment]
In theory:

* possibly install an extension for syntax highlighting and configure vscode to use that for your file extension 
* set the "Allow Breakpoints Anywhere" option (because this extension currently does not register assembly and also every extension seems to set a special language id for that)
* just debug as commonly

**Comment by GitMensch** [comment]
@Epikest Did that solved your issue? If not how did you go on with it?

**Comment by GitMensch** [comment]
@Epikest Was this about "how to debug assembly" as I've understood it or is this about showing the disassembly which is tracked in #321?

**Comment by Epikest** [comment]
sorry for not replying, this has been resolved
