### ISSUE TITLE
can't add breakpoints on source code panel on aarch64

### ISSUE THREAD

**Issue by runninghorse2016** [WebFreak001/code-debug#276]
The environment info is as follows:
Linux 5.4.18-27-generic aarch64
gdb 9.1
vscode 1.58

after installing this extension, i can debug my c++ code.
i can add breakpoints through the breakpoints view, but the red point doesn't show on the source code.
And i can't add breakpoints on source code panel, is it normal?

**Comment by runninghorse2016** [comment]
I tested it on ubuntu 18.04 on x86_64, it worked.
Is it something to be configured on arm64?

**Comment by reticenceji** [comment]
I meet similar problem when I debug with rust in riscv64. The environment info as follows:
riscv64-unknown-elf-gdb 8.3
vscode 1.58
qemu 5.0.0

But if I add `"showDevDebugOutput": true,` in launch.json, I can add breakpoint in main panal, otherwise I can only add breakpoint in debug console. I wonder how we communicate with gdb and vscode.

**Comment by brownts** [comment]
Hi @runninghorse2016 , this may be the same issue as described in #233 and #292 and fixed in #280.  Is it possible you were using a different version of VSCode on x86_64?  The fix was to change a configuration that had been deprecated in VSCode at some point in the past, thus it did work on older versions of VSCode.  The fix mentioned, should be in the next release of this extension.

If this truly is the problem, you should be able to work around this until a new version of the extension is released by adjusting your setting in VSCode to allow setting breakpoints anywhere:

- File > Preferences > Settings > Features > Debug
  - Enable the "Allow Breakpoints Everywhere" setting

@reticenceji, your issue sounds different than what is described by @runninghorse2016.  The original problem description describes trouble setting a breakpoint by clicking on the left margin in a source code file (i.e., "red point ... source code file").  Your problem sounds different in that you are having trouble with breakpoints in the panel.  It might be good for you to create a new issue if that is still a problem.

**Comment by GitMensch** [comment]
Closed as "should be fixed", @runninghorse2016 an update would be nice, @reticenceji you may want to recheck if your issue still occurs and if yes, open a new issue for this.
