### ISSUE TITLE
make support

### ISSUE THREAD

**Issue by JanKok** [WebFreak001/code-debug#41]
I added `"preLaunchTask": "make"` to launch.json and

```
{
	"version": "0.1.0",
	"command": "make",
	"isShellCommand": false,
	// Show the output window only if unrecognized errors occur.
	"showOutput": "always", //"silent",

	// use the standard tsc problem matcher to find compile problems
	// in the output.
	"problemMatcher": "$tsc"
}
```

in tasks.json and now make runs each time I click start, which is pretty good. But,
1. If there are compile errors (resulting in make returning an error value), Code doesn't stop. It tries to run the program anyway.
2. The make output window appears momentarily but is replaced with the debug console (which BTW displays the cryptic message `undefined=thread-group-added,id="i1"`). I'd like the output window to remain visible if there are make errors.
3. F8, Ctrl-Shift-M etc., don't work to let me visit the errors in my source code. What does it take to make that work?

I would suggest you provide a more extensive launch.json and a tasks.json file tailored to C/C++ development and with some comments, similar to the default tasks.json file. That would enable new users to get started more quickly.

**Comment by WebFreak001** [comment]
1. Might be better to report it to Microsoft, I can't handle that because its completely handled by vscode
2. That the output window gets replaced is also because of vscode. Maybe give them a suggestion for tabs in the output view at the bottom to separate debugger and the output windows and the task window
3. Not sure what F8, Ctrl-Shift-M should do. The tasks.json and preLaunchTask is completely handled by vscode and I can't control what it does

Also for C/C++: First im not a C/C++ developer and I dont really know how these tools like make work, second its out of scope for just a debugger. The tasks.json file is good enough for this and any suggestions might be better on vscode's side. I am basically using everything vscode allows a debugger extension to do. It actually cant even read the launch.json or any files directly without using the node.js filesystem library. So that would also be unsafe and might break in future releases

**Comment by JanKok** [comment]
There seems to be some confusion about what is the "February release", "March release", etc. But anyway VSCode v0.10.10 dated 2016-03-07 does work better and does avoid launching if the preLaunchTask returns an error. Thanks for letting me know!
