### ISSUE TITLE
Extension crashes when there is non-ascii output

### ISSUE THREAD

**Issue by fallenwood** [WebFreak001/code-debug#77]
gdb version: `GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git`
os version: `ubuntu 16.10 x64`

screenshot
![image](http://oe1gpj47f.bkt.clouddn.com/native-debug.jpg)

here is the code

``` c++
#include <iostream>
int main(int argc, char *argv[]) {
  std::cout << "好好学习，天天向上" << std::endl;
  std::cout << "lalala" << std::endl;
}
```

**Comment by WebFreak001** [comment]
This line is causing the issue:

```
~"4\t  std::cout << \"\345\245\275\345\245\275\345\255\246\344\271\240\357\274\214\345\244\251\345\244\251\345\220\221\344\270\212\" << std::endl;\n"
```

My string parsing code (just finding the length and then using JSON.parse) crashes there because `\345` can't be parsed to a string using the JSON string parser. I am not sure how I can parse this string because that does not seem to be one byte in the string and it also isn't the correct unicode char code.

One dirty fix would be just outputting the string without parsing it. This would also mean that variables containing chinese characters won't be displayed properly.

I would prefer to parse it correctly though, so the variables view works for every language. I just need to figure out what kind of formatting that is.
