### ISSUE TITLE
Native debug on macOS is becoming inoperable with each VSCode update

### ISSUE THREAD

**Issue by jecse** [WebFreak001/code-debug#80]
The native debug extension is becoming unusable with each update of VS Code for macOS. The lldb-mi option to display the local variables capability vanished after 1.5. The gdb extension is not unusable anymore because it appears to ignore breakpoints. It would be nice to get this extension working as it was with VS Code 1.4.

**Comment by WebFreak001** [comment]
hm seems to really only be happening on osx then, everything still works on my linux machine. I can't really test this though because I dont have a mac.

Can you try to debug again, but enable `"printCalls": true` and `"showDevDebugOutput": true` in your debugger config and send me a screenshot/content of the log for a simple hello world program?

**Comment by nobig** [comment]
It's not limited to OS X. As long as there is at any blank space present in the folder path leading to the binary, the extension will fail to load the breakpoints.

**Comment by WebFreak001** [comment]
oh right that should be fixable, gonna look into it later

**Comment by WebFreak001** [comment]
weird, I am already escaping the path to the executable and also putting quotes around it. For me on linux I also don't have any problems with spaces in the path. No problems if the workspace path contains spaces and no problems if the folder in `target` contains a space.

Are you sure the path to the executable actually exists? Its built using `workspace root + config.target`, so the project path `/home/webfreak/dev/GDBTest` with the `target` option in the config set to `gdbtest` would run `/home/webfreak/dev/GDBTest/gdbtest`

**Comment by nobig** [comment]
I have checked it, and apparently, the mi commands are lacking quotes when passed to gdb.

So it is passing
`-break-insert -f /file/path/with/spaces on it/main`
instead of
`-break-insert -f "/file/path/with/spaces on it/main"`
so gdb tries to look for a file called "/file/path/with/spaces" instead of the actual executable.

I hope that helps.
